apiVersion: 1

datasources:
  - name: InfluxDB-ATMOS
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG:-atmos}
      defaultBucket: ${INFLUX_BUCKET:-telemetry}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true
    editable: false
